- id: '1735577184308'
  alias: Turn on Dehumidifier
  description: ''
  triggers:
  - value_template: '{{ states(''sensor.aqara_bh2_on_wall_temperature_2'') | float
      < (states(''sensor.well_shed_target_temperature'') | float - 1) }}

      '
    trigger: template
  conditions: []
  actions:
  - type: turn_on
    device_id: 0691808aefe989c8bb43a9413d476dc1
    entity_id: 39d124a07772e2c67ecf740a47e05379
    domain: switch
  mode: single
- id: '1735577543920'
  alias: Turn off Dehumidifier and Space Heater
  description: ''
  triggers:
  - value_template: '{{ states(''sensor.aqara_bh2_on_wall_temperature_2'') | float
      > (states(''sensor.well_shed_target_temperature'') | float + 1) }}

      '
    trigger: template
  conditions: []
  actions:
  - type: turn_off
    device_id: 0691808aefe989c8bb43a9413d476dc1
    entity_id: 39d124a07772e2c67ecf740a47e05379
    domain: switch
  - type: turn_off
    device_id: fa9a84d0cf30e26215c1f2f73f9c300a
    entity_id: 7b460f2ccfe7a2d8ba8648334ea6c01b
    domain: switch
  - action: notify.mobile_app_pixel_8
    metadata: {}
    data:
      message: Dehumidifier and heater have been turned off
    alias: Send a notification to Mark's phone
    enabled: false
  mode: single
- id: '1737297383581'
  alias: Turn on Space Heater
  description: ''
  triggers:
  - value_template: '{{ states(''sensor.aqara_bh2_on_wall_temperature_2'') | float
      < (states(''sensor.well_shed_target_temperature'') | float - 1.5) }}

      '
    trigger: template
  conditions: []
  actions:
  - type: turn_on
    device_id: fa9a84d0cf30e26215c1f2f73f9c300a
    entity_id: 7b460f2ccfe7a2d8ba8648334ea6c01b
    domain: switch
  mode: single
- id: '1737303859441'
  alias: Notify app on low Well Shed temp
  description: ''
  triggers:
  - alias: When the Well Shed temp falls to 3 degrees below the target temp
    value_template: '{{ states(''sensor.aqara_bh2_on_wall_temperature_2'') | float
      < (states(''sensor.well_shed_target_temperature'') | float - 3) }}

      '
    trigger: template
  conditions: []
  actions:
  - alias: Send a notification to Mark's phone
    action: notify.mobile_app_pixel_8
    metadata: {}
    data:
      message: The well shed temp has fallen to 3 degrees below the target temp!
  mode: single
- id: '1737305396283'
  alias: Check Inside Temp Sensor
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.inside_thermometer_connection
    from: 'on'
    to: 'off'
  conditions: []
  actions:
  - action: notify.mobile_app_pixel_8
    metadata: {}
    data:
      message: Inside temp sensor has been inactive a long time
  mode: single
- id: '1737336900703'
  alias: Check Outside Temp Sensor
  description: ''
  triggers:
  - alias: Outside Temp Sensor becomes inactive
    trigger: state
    entity_id:
    - binary_sensor.outside_thermometer_connection
    from: 'on'
    to: 'off'
  conditions: []
  actions:
  - alias: Notify Mark via the companion phone app
    action: notify.mobile_app_pixel_8
    metadata: {}
    data:
      message: The outside temp sensor has been inactive a long time
      title: Hello?
  mode: single
- id: '1738506533020'
  alias: Turn on Heat
  description: ''
  triggers:
  - value_template: '{{ states(''sensor.aqara_bh2_on_wall_temperature_2'') | float
      < (states(''sensor.well_shed_target_temperature'') | float - 1) }}

      '
    trigger: template
  conditions: []
  actions:
  - if:
    - condition: numeric_state
      entity_id: sensor.aqara_bh2_on_wall_humidity_2
      above: 55
    then:
    - type: turn_on
      device_id: 0691808aefe989c8bb43a9413d476dc1
      entity_id: 39d124a07772e2c67ecf740a47e05379
      domain: switch
    else:
    - type: turn_on
      device_id: fa9a84d0cf30e26215c1f2f73f9c300a
      entity_id: 7b460f2ccfe7a2d8ba8648334ea6c01b
      domain: switch
  mode: single
- id: '1738591521483'
  alias: Notify app if Dehumidifier is on but not drawing current
  description: ''
  triggers:
  - type: turned_on
    device_id: 0691808aefe989c8bb43a9413d476dc1
    entity_id: 39d124a07772e2c67ecf740a47e05379
    domain: switch
    trigger: device
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions:
  - condition: numeric_state
    entity_id: sensor.sp26_energy_power
    below: 100
  actions:
  - action: notify.mobile_app_pixel_8
    metadata: {}
    data:
      message: The dehumidifier is on but not drawing current. Could the internal
        reservoir be full?
  mode: single
- id: '1739238546687'
  alias: Help the Damn Dehumidifier
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.sp26_energy_power
    for:
      hours: 0
      minutes: 3
      seconds: 0
    above: 10
    below: 40
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.sp27
  mode: single
